@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJBcnF1aXRlY3RvIiwiaWF0IjoxNzc1NzY4NDY1LCJleHAiOjE3NzU4MDQ0NjV9.FAGgYpTCget5cdWYr0jSS0TvG_WDjbZGMlLk2UjzS1U
POST http://localhost:4321/auth/register
Content-Type: application/json

{
  "username": "Arquitecto",
  "email": "arquitecto@clase.edu",
  "password": "miPasswo21"
}

### Login usuario (token JWT)
POST http://localhost:4321/auth/login
Content-Type: application/json

{
    "username": "Arquitecto",
    "password": "miPasswo21"
}

### Consultar todas las peliculas (requiere JWT)
GET http://localhost:4321/movies
Authorization: Bearer {{token}}
### Consultar pelicula por id (requiere JWT)
GET http://localhost:4321/movies/2
Authorization: Bearer {{token}}
### Crear pelicula (requiere JWT)
POST http://localhost:4321/movies
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Scary Movie 3",
    "release_year": 2003,
    "synopsis": "Una parodia de las películas de terror populares en ese momento, como 'The Ring' y 'The Matrix'.",
    "genres": [1,2],
    "directors": [2,3]
}

### Actualizar pelicula (requiere JWT)
PUT http://localhost:4321/movies/4
Content-Type: application/json
Authorization: Bearer {{token}}

{

    "title": "The Matrix Reloaded",
    "directors": [4,6]
}

### Eliminar pelicula (requiere JWT)
DELETE http://localhost:4321/movies/
Authorization: Bearer {{token}}

### Crear director (requiere JWT)
POST http://localhost:4321/directors
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "full_name": "Martin Scorsese"
}
###  Relacionar con director 
PUT http://localhost:4321/movies/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "directors": [3]
}


### Actualizar director (requiere JWT)
PUT http://localhost:4321/directors/7
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "full_name": "Steven Spielberg"
}

### Eliminar director (requiere JWT)
DELETE http://localhost:4321/directors/3
Authorization: Bearer {{token}}

### Probar token en endpoint de prueba
GET http://localhost:4321/test-db
Authorization: Bearer 

### Consultar todos los géneros (requiere JWT)
GET http://localhost:4321/genres
Authorization: Bearer {{token}}

### Consultar género por id (requiere JWT)
GET http://localhost:4321/genres/1
Authorization: Bearer {{token}}

### Crear género (requiere JWT)
POST http://localhost:4321/genres
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Sobrenatural"
}

### Actualizar género (requiere JWT)
PUT http://localhost:4321/genres/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Post-apocaliptico"
}

### Eliminar género (requiere JWT)
DELETE http://localhost:4321/genres/2
Authorization: Bearer {{token}}
